# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Build
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2
        with:
          repository: hangxingliu/canvas-datagrid
          path: canvas-datagrid
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          # cache: 'npm'
      - run: cd canvas-datagrid && pwd && npm install && npm run build
      - run: cd canvas-datagrid && ls -al dist
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: canvas-datagrid/dist
