# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Test and Build
on:
  push:
  workflow_dispatch:
    inputs:
      repo_branch:
        description: 'The branch name of the repo "hangxingliu/canvas-datagrid"'
        default: 'master'
        required: true
        type: string

jobs:
  is-push-to-main:
    runs-on: ubuntu-latest
    name: 'Is triggered by push to main?'
    if: ${{
      (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') &&
      (github.event_name == 'push') }}
    steps:
      - name: 'Current action is triggered by push to main/master'
        run: 'true'

  build-for-push:
    runs-on: ubuntu-latest
    needs: is-push-to-main
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2
        with:
          repository: hangxingliu/canvas-datagrid
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: pwd && ls -al && npm install && npm run test && ls -al dist
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  build-for-click:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2
        with:
          repository: hangxingliu/canvas-datagrid
          ref: ${{ github.event.inputs.repo_branch }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: git log -n 1 --oneline --branches;
      - run: pwd && ls -al && npm install && npm run test && ls -al dist
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
